/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
declare module "@drincs/pixi-vn/characters" {
    interface PixivnCharacterIds {
        "mc": never;
        "james": never;
        "steph": never;
        "sly": never;
    }
}
declare module "@drincs/pixi-vn/narration" {
    interface PixivnLabelIds {
        "animation_01": never;
        "second_part": never;
        "start": never;
    }
}
export const characterIds = ["mc","james","steph","sly"] as const;
export const characterIdsEnum = {"mc":"mc","james":"james","steph":"steph","sly":"sly"} as const;
export const labelIds = ["animation_01","second_part","start"] as const;
export const labelIdsEnum = {"animation_01":"animation_01","second_part":"second_part","start":"start"} as const;
