/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NarrationRouteImport } from './routes/narration'
import { Route as IndexRouteImport } from './routes/index'

const NarrationRoute = NarrationRouteImport.update({
  id: '/narration',
  path: '/narration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/narration': typeof NarrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/narration': typeof NarrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/narration': typeof NarrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/narration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/narration'
  id: '__root__' | '/' | '/narration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NarrationRoute: typeof NarrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/narration': {
      id: '/narration'
      path: '/narration'
      fullPath: '/narration'
      preLoaderRoute: typeof NarrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NarrationRoute: NarrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
